
package tn.esprit.erpbi.banque.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServiceCompteService", targetNamespace = "http://services.banque.erpbi.esprit.tn/", wsdlLocation = "http://localhost:18080/banque-ejb/CompteService?wsdl")
public class ServiceCompteService
    extends Service
{

    private final static URL SERVICECOMPTESERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICECOMPTESERVICE_EXCEPTION;
    private final static QName SERVICECOMPTESERVICE_QNAME = new QName("http://services.banque.erpbi.esprit.tn/", "ServiceCompteService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:18080/banque-ejb/CompteService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICECOMPTESERVICE_WSDL_LOCATION = url;
        SERVICECOMPTESERVICE_EXCEPTION = e;
    }

    public ServiceCompteService() {
        super(__getWsdlLocation(), SERVICECOMPTESERVICE_QNAME);
    }

    public ServiceCompteService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICECOMPTESERVICE_QNAME, features);
    }

    public ServiceCompteService(URL wsdlLocation) {
        super(wsdlLocation, SERVICECOMPTESERVICE_QNAME);
    }

    public ServiceCompteService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICECOMPTESERVICE_QNAME, features);
    }

    public ServiceCompteService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceCompteService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ComptePortType
     */
    @WebEndpoint(name = "ComptePort")
    public ComptePortType getComptePort() {
        return super.getPort(new QName("http://services.banque.erpbi.esprit.tn/", "ComptePort"), ComptePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ComptePortType
     */
    @WebEndpoint(name = "ComptePort")
    public ComptePortType getComptePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.banque.erpbi.esprit.tn/", "ComptePort"), ComptePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICECOMPTESERVICE_EXCEPTION!= null) {
            throw SERVICECOMPTESERVICE_EXCEPTION;
        }
        return SERVICECOMPTESERVICE_WSDL_LOCATION;
    }

}
