package com.esprit.hypnotrip.persistence;
// Generated 19 nov. 2016 19:30:02 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Aspnetuserclaims generated by hbm2java
 */
@Entity
@Table(name = "aspnetuserclaims", catalog = "hypnodb")
public class Aspnetuserclaims implements java.io.Serializable {

	private Integer id;
	private String claimType;
	private String claimValue;
	private String userId;

	public Aspnetuserclaims() {
	}

	public Aspnetuserclaims(String claimType, String claimValue, String userId) {
		this.claimType = claimType;
		this.claimValue = claimValue;
		this.userId = userId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ClaimType", length = 128)
	public String getClaimType() {
		return this.claimType;
	}

	public void setClaimType(String claimType) {
		this.claimType = claimType;
	}

	@Column(name = "ClaimValue", length = 128)
	public String getClaimValue() {
		return this.claimValue;
	}

	public void setClaimValue(String claimValue) {
		this.claimValue = claimValue;
	}

	@Column(name = "UserId", length = 128)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

}
