package com.esprit.hypnotrip.persistence;
// Generated 19 nov. 2016 19:30:02 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Aspnetuserlogins generated by hbm2java
 */
@Entity
@Table(name = "aspnetuserlogins", catalog = "hypnodb")
public class Aspnetuserlogins implements java.io.Serializable {

	private AspnetuserloginsId id;

	public Aspnetuserlogins() {
	}

	public Aspnetuserlogins(AspnetuserloginsId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "loginProvider", column = @Column(name = "LoginProvider", nullable = false, length = 128) ),
			@AttributeOverride(name = "providerKey", column = @Column(name = "ProviderKey", nullable = false, length = 128) ),
			@AttributeOverride(name = "userId", column = @Column(name = "UserId", nullable = false, length = 128) ) })
	public AspnetuserloginsId getId() {
		return this.id;
	}

	public void setId(AspnetuserloginsId id) {
		this.id = id;
	}

}
