package com.esprit.hypnotrip.persistence;
// Generated 19 nov. 2016 19:30:02 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Aspnetroles generated by hbm2java
 */
@Entity
@Table(name = "aspnetroles", catalog = "hypnodb", uniqueConstraints = @UniqueConstraint(columnNames = "Name") )
public class Aspnetroles implements java.io.Serializable {

	private String id;
	private String name;

	public Aspnetroles() {
	}

	public Aspnetroles(String id, String name) {
		this.id = id;
		this.name = name;
	}

	@Id

	@Column(name = "Id", unique = true, nullable = false, length = 128)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "Name", unique = true, nullable = false, length = 128)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
