package com.esprit.hypnotrip.persistence;
// Generated 19 nov. 2016 19:30:02 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Belongs generated by hbm2java
 */
@Entity
@Table(name = "belongs", catalog = "hypnodb")
public class Belongs implements java.io.Serializable {

	private BelongsId id;
	private int flag;

	public Belongs() {
	}

	public Belongs(BelongsId id, int flag) {
		this.id = id;
		this.flag = flag;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "cercleId", column = @Column(name = "CercleId", nullable = false) ),
			@AttributeOverride(name = "date", column = @Column(name = "date", nullable = false, length = 0) ),
			@AttributeOverride(name = "userId", column = @Column(name = "UserId", nullable = false, length = 128) ) })
	public BelongsId getId() {
		return this.id;
	}

	public void setId(BelongsId id) {
		this.id = id;
	}

	@Column(name = "flag", nullable = false)
	public int getFlag() {
		return this.flag;
	}

	public void setFlag(int flag) {
		this.flag = flag;
	}

}
