package com.esprit.hypnotrip.persistence;
// Generated 19 nov. 2016 19:30:02 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BelongsId generated by hbm2java
 */
@Embeddable
public class BelongsId implements java.io.Serializable {

	private int cercleId;
	private Date date;
	private String userId;

	public BelongsId() {
	}

	public BelongsId(int cercleId, Date date, String userId) {
		this.cercleId = cercleId;
		this.date = date;
		this.userId = userId;
	}

	@Column(name = "CercleId", nullable = false)
	public int getCercleId() {
		return this.cercleId;
	}

	public void setCercleId(int cercleId) {
		this.cercleId = cercleId;
	}

	@Column(name = "date", nullable = false, length = 0)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "UserId", nullable = false, length = 128)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BelongsId))
			return false;
		BelongsId castOther = (BelongsId) other;

		return (this.getCercleId() == castOther.getCercleId())
				&& ((this.getDate() == castOther.getDate()) || (this.getDate() != null && castOther.getDate() != null
						&& this.getDate().equals(castOther.getDate())))
				&& ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null
						&& castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCercleId();
		result = 37 * result + (getDate() == null ? 0 : this.getDate().hashCode());
		result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
		return result;
	}

}
