package com.esprit.hypnotrip.persistence;
// Generated 19 nov. 2016 19:30:02 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Buy generated by hbm2java
 */
@Entity
@Table(name = "buy", catalog = "hypnodb")
public class Buy implements java.io.Serializable {

	private BuyId id;

	public Buy() {
	}

	public Buy(BuyId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "offerId", column = @Column(name = "OfferId", nullable = false) ),
			@AttributeOverride(name = "userId", column = @Column(name = "UserId", nullable = false, length = 128) ) })
	public BuyId getId() {
		return this.id;
	}

	public void setId(BuyId id) {
		this.id = id;
	}

}
