package com.esprit.hypnotrip.persistence;
// Generated 19 nov. 2016 19:30:02 by Hibernate Tools 4.3.1.Final

import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Buy generated by hbm2java
 */
@Entity
@Table(name = "buy", catalog = "hypnodb")
public class Buy implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private BuyId id;

	private User user;

	private Offer offer;

	public Buy() {
	}

	public Buy(User user, Offer offer) {
		super();
		this.user = user;
		this.offer = offer;
	}

	public Buy(BuyId id) {
		this.id = id;
	}

	@EmbeddedId
	public BuyId getId() {
		return this.id;
	}

	public void setId(BuyId id) {
		this.id = id;
	}

	@ManyToOne
	@JoinColumn(name = "userId", referencedColumnName = "id", updatable = false, insertable = false)
	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@ManyToOne
	@JoinColumn(name = "offerId", referencedColumnName = "pageId", updatable = false, insertable = false)
	public Offer getOffer() {
		return offer;
	}

	public void setOffer(Offer offer) {
		this.offer = offer;
	}

}
