package com.esprit.hypnotrip.persistence;
// Generated 19 nov. 2016 19:30:02 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CommentsId generated by hbm2java
 */
@Embeddable
public class CommentsId implements java.io.Serializable {

	private Date commentDate;
	private int postId;
	private String userId;

	public CommentsId() {
	}

	public CommentsId(Date commentDate, int postId, String userId) {
		this.commentDate = commentDate;
		this.postId = postId;
		this.userId = userId;
	}

	@Column(name = "CommentDate", nullable = false, length = 0)
	public Date getCommentDate() {
		return this.commentDate;
	}

	public void setCommentDate(Date commentDate) {
		this.commentDate = commentDate;
	}

	@Column(name = "PostId", nullable = false)
	public int getPostId() {
		return this.postId;
	}

	public void setPostId(int postId) {
		this.postId = postId;
	}

	@Column(name = "UserId", nullable = false, length = 128)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CommentsId))
			return false;
		CommentsId castOther = (CommentsId) other;

		return ((this.getCommentDate() == castOther.getCommentDate()) || (this.getCommentDate() != null
				&& castOther.getCommentDate() != null && this.getCommentDate().equals(castOther.getCommentDate())))
				&& (this.getPostId() == castOther.getPostId())
				&& ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null
						&& castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCommentDate() == null ? 0 : this.getCommentDate().hashCode());
		result = 37 * result + this.getPostId();
		result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
		return result;
	}

}
