package com.esprit.hypnotrip.persistence;
// Generated 19 nov. 2016 19:30:02 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ComplainsId generated by hbm2java
 */
@Embeddable
public class ComplainsId implements java.io.Serializable {

	private Date commentedDate;
	private int postId;
	private String urId;
	private String userId;

	public ComplainsId() {
	}

	public ComplainsId(Date commentedDate, int postId, String urId, String userId) {
		this.commentedDate = commentedDate;
		this.postId = postId;
		this.urId = urId;
		this.userId = userId;
	}

	@Column(name = "CommentedDate", nullable = false, length = 0)
	public Date getCommentedDate() {
		return this.commentedDate;
	}

	public void setCommentedDate(Date commentedDate) {
		this.commentedDate = commentedDate;
	}

	@Column(name = "PostId", nullable = false)
	public int getPostId() {
		return this.postId;
	}

	public void setPostId(int postId) {
		this.postId = postId;
	}

	@Column(name = "UrId", nullable = false, length = 128)
	public String getUrId() {
		return this.urId;
	}

	public void setUrId(String urId) {
		this.urId = urId;
	}

	@Column(name = "UserId", nullable = false, length = 128)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ComplainsId))
			return false;
		ComplainsId castOther = (ComplainsId) other;

		return ((this.getCommentedDate() == castOther.getCommentedDate())
				|| (this.getCommentedDate() != null && castOther.getCommentedDate() != null
						&& this.getCommentedDate().equals(castOther.getCommentedDate())))
				&& (this.getPostId() == castOther.getPostId())
				&& ((this.getUrId() == castOther.getUrId()) || (this.getUrId() != null && castOther.getUrId() != null
						&& this.getUrId().equals(castOther.getUrId())))
				&& ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null
						&& castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCommentedDate() == null ? 0 : this.getCommentedDate().hashCode());
		result = 37 * result + this.getPostId();
		result = 37 * result + (getUrId() == null ? 0 : this.getUrId().hashCode());
		result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
		return result;
	}

}
