package com.esprit.hypnotrip.persistence;
// Generated 19 nov. 2016 19:30:02 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Event generated by hbm2java
 */
@Entity
@Table(name = "event", catalog = "hypnodb")
public class Event implements java.io.Serializable {

	private int pageId;
	private Date dateOfEvent;
	private float latitude;
	private float longitude;

	public Event() {
	}

	public Event(int pageId, Date dateOfEvent, float latitude, float longitude) {
		this.pageId = pageId;
		this.dateOfEvent = dateOfEvent;
		this.latitude = latitude;
		this.longitude = longitude;
	}

	@Id

	@Column(name = "PageId", unique = true, nullable = false)
	public int getPageId() {
		return this.pageId;
	}

	public void setPageId(int pageId) {
		this.pageId = pageId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateOfEvent", nullable = false, length = 0)
	public Date getDateOfEvent() {
		return this.dateOfEvent;
	}

	public void setDateOfEvent(Date dateOfEvent) {
		this.dateOfEvent = dateOfEvent;
	}

	@Column(name = "Latitude", nullable = false, precision = 12, scale = 0)
	public float getLatitude() {
		return this.latitude;
	}

	public void setLatitude(float latitude) {
		this.latitude = latitude;
	}

	@Column(name = "Longitude", nullable = false, precision = 12, scale = 0)
	public float getLongitude() {
		return this.longitude;
	}

	public void setLongitude(float longitude) {
		this.longitude = longitude;
	}

}
