package com.esprit.hypnotrip.persistence;
// Generated 19 nov. 2016 19:30:02 by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FollowsId generated by hbm2java
 */
@Embeddable
public class FollowsId implements java.io.Serializable {

	private Date dateFollow;
	private int pageId;
	private String userId;

	public FollowsId() {
	}

	public FollowsId(Date dateFollow, int pageId, String userId) {
		this.dateFollow = dateFollow;
		this.pageId = pageId;
		this.userId = userId;
	}

	@Column(name = "DateFollow", nullable = false, length = 0)
	public Date getDateFollow() {
		return this.dateFollow;
	}

	public void setDateFollow(Date dateFollow) {
		this.dateFollow = dateFollow;
	}

	@Column(name = "PageId", nullable = false)
	public int getPageId() {
		return this.pageId;
	}

	public void setPageId(int pageId) {
		this.pageId = pageId;
	}

	@Column(name = "UserId", nullable = false, length = 128)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FollowsId))
			return false;
		FollowsId castOther = (FollowsId) other;

		return ((this.getDateFollow() == castOther.getDateFollow()) || (this.getDateFollow() != null
				&& castOther.getDateFollow() != null && this.getDateFollow().equals(castOther.getDateFollow())))
				&& (this.getPageId() == castOther.getPageId())
				&& ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null
						&& castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getDateFollow() == null ? 0 : this.getDateFollow().hashCode());
		result = 37 * result + this.getPageId();
		result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
		return result;
	}

	@Override
	public String toString() {
		return "FollowsId [dateFollow=" + dateFollow + ", pageId=" + pageId + ", userId=" + userId + "]";
	}

	public FollowsId(String userId,int pageId) {
		this.userId = userId;
		this.pageId = pageId;
		this.dateFollow = new Date();
	}

}
