package com.esprit.hypnotrip.persistence;
// Generated 19 nov. 2016 19:30:02 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Follows generated by hbm2java
 */
@Entity
@Table(name = "follows", catalog = "hypnodb")
public class Follows implements java.io.Serializable {

	private FollowsId id;
	private boolean followStat;

	

	private User user ;
	private Pages pages;
	
	
	public Follows() {
	}

	public Follows(FollowsId id, boolean followStat) {
		this.id = id;
		this.followStat = followStat;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "dateFollow", column = @Column(name = "DateFollow", nullable = false, length = 0) ),
			@AttributeOverride(name = "pageId", column = @Column(name = "PageId", nullable = false) ),
			@AttributeOverride(name = "userId", column = @Column(name = "UserId", nullable = false, length = 128) ) })
	public FollowsId getId() {
		return this.id;
	}

	public void setId(FollowsId id) {
		this.id = id;
	}

	@Column(name = "FollowStat", nullable = false)
	public boolean isFollowStat() {
		return this.followStat;
	}

	public void setFollowStat(boolean followStat) {
		this.followStat = followStat;
	}

	@ManyToOne
	@JoinColumn(name="userId", referencedColumnName="id",updatable=false , insertable= false)
	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@ManyToOne
	@JoinColumn(name="pageId", referencedColumnName="pageId",updatable=false , insertable= false)
	public Pages getPages() {
		return pages;
	}

	public void setPages(Pages pages) {
		this.pages = pages;
	}

	@Override
	public String toString() {
		return "Follows [id=" + id + ", followStat=" + followStat + "]";
	}

	
}
