package com.esprit.hypnotrip.persistence;
// Generated 19 nov. 2016 19:30:02 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Invitations generated by hbm2java
 */
@Entity
@Table(name = "invitations", catalog = "hypnodb")
public class Invitations implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private InvitationsId id;
	private int pageId;
	private String description;
	private int invitationStatus;

	private User sender;

	private User reciever;

	public Invitations() {
	}

	public Invitations(int pageId, String description, int invitationStatus, User sender, User reciever) {
		super();
		this.description = description;
		this.pageId = pageId;
		this.invitationStatus = invitationStatus;
		this.sender = sender;
		this.reciever = reciever;
		this.id = new InvitationsId(reciever.getId(), sender.getId());
	}

	public Invitations(int pageId, int invitationStatus, User sender, User reciever) {
		super();
		this.pageId = pageId;
		this.invitationStatus = invitationStatus;
		this.sender = sender;
		this.reciever = reciever;
		this.id = new InvitationsId(reciever.getId(), sender.getId());
	}

	public Invitations(InvitationsId id, String description, int pageId) {
		this.id = id;
		this.description = description;
		this.pageId = pageId;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "receiverUserId", column = @Column(name = "ReceiverUserId", nullable = false, length = 128)),
			@AttributeOverride(name = "senderUserId", column = @Column(name = "SenderUserId", nullable = false, length = 128)) })
	public InvitationsId getId() {
		return this.id;
	}

	public void setId(InvitationsId id) {
		this.id = id;
	}

	@Column(name = "Description", nullable = true)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "PageId", nullable = false)
	public int getPageId() {
		return this.pageId;
	}

	public void setPageId(int pageId) {
		this.pageId = pageId;
	}

	@ManyToOne
	@JoinColumn(name = "senderUserId", referencedColumnName = "id", updatable = false, insertable = false)
	public User getSender() {
		return sender;
	}

	public void setSender(User sender) {
		this.sender = sender;
	}

	@ManyToOne
	@JoinColumn(name = "receiverUserId", referencedColumnName = "id", updatable = false, insertable = false)
	public User getReciever() {
		return reciever;
	}

	public void setReciever(User reciever) {
		this.reciever = reciever;
	}

	public int getInvitationStatus() {
		return invitationStatus;
	}

	public void setInvitationStatus(int invitationStatus) {
		this.invitationStatus = invitationStatus;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Invitations other = (Invitations) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Invitations [pageId=" + pageId + ", description=" + description + ", invitationStatus="
				+ invitationStatus + ", sender=" + sender.getId() + ", reciever=" + reciever.getId() + "]";
	}

}
