package com.esprit.hypnotrip.persistence;
// Generated 19 nov. 2016 19:30:02 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Invitations generated by hbm2java
 */
@Entity
@Table(name = "invitations", catalog = "hypnodb")
public class Invitations implements java.io.Serializable {

	private InvitationsId id;
	private String description;
	private int pageId;
	private Date sentDate;

	public Invitations() {
	}

	public Invitations(InvitationsId id, int pageId, Date sentDate) {
		this.id = id;
		this.pageId = pageId;
		this.sentDate = sentDate;
	}

	public Invitations(InvitationsId id, String description, int pageId, Date sentDate) {
		this.id = id;
		this.description = description;
		this.pageId = pageId;
		this.sentDate = sentDate;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "receiverUserId", column = @Column(name = "ReceiverUserId", nullable = false, length = 128) ),
			@AttributeOverride(name = "senderUserId", column = @Column(name = "SenderUserId", nullable = false, length = 128) ) })
	public InvitationsId getId() {
		return this.id;
	}

	public void setId(InvitationsId id) {
		this.id = id;
	}

	@Column(name = "Description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "PageId", nullable = false)
	public int getPageId() {
		return this.pageId;
	}

	public void setPageId(int pageId) {
		this.pageId = pageId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SentDate", nullable = false, length = 0)
	public Date getSentDate() {
		return this.sentDate;
	}

	public void setSentDate(Date sentDate) {
		this.sentDate = sentDate;
	}

}
