package com.esprit.hypnotrip.persistence;
// Generated 19 nov. 2016 19:30:02 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * InvitationsId generated by hbm2java
 */
@Embeddable
public class InvitationsId implements java.io.Serializable {

	private String receiverUserId;
	private String senderUserId;

	public InvitationsId() {
	}

	public InvitationsId(String receiverUserId, String senderUserId) {
		this.receiverUserId = receiverUserId;
		this.senderUserId = senderUserId;
	}

	@Column(name = "ReceiverUserId", nullable = false, length = 128)
	public String getReceiverUserId() {
		return this.receiverUserId;
	}

	public void setReceiverUserId(String receiverUserId) {
		this.receiverUserId = receiverUserId;
	}

	@Column(name = "SenderUserId", nullable = false, length = 128)
	public String getSenderUserId() {
		return this.senderUserId;
	}

	public void setSenderUserId(String senderUserId) {
		this.senderUserId = senderUserId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InvitationsId))
			return false;
		InvitationsId castOther = (InvitationsId) other;

		return ((this.getReceiverUserId() == castOther.getReceiverUserId())
				|| (this.getReceiverUserId() != null && castOther.getReceiverUserId() != null
						&& this.getReceiverUserId().equals(castOther.getReceiverUserId())))
				&& ((this.getSenderUserId() == castOther.getSenderUserId())
						|| (this.getSenderUserId() != null && castOther.getSenderUserId() != null
								&& this.getSenderUserId().equals(castOther.getSenderUserId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getReceiverUserId() == null ? 0 : this.getReceiverUserId().hashCode());
		result = 37 * result + (getSenderUserId() == null ? 0 : this.getSenderUserId().hashCode());
		return result;
	}

}
