package com.esprit.hypnotrip.persistence;
// Generated 19 nov. 2016 19:30:02 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Invitations generated by hbm2java
 */
@Entity
@Table(name = "invitations", catalog = "hypnodb")
public class Invitations implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private InvitationsId id;
	private String description;
	private int pageId;

	private User sender;

	private User reciever;

	public Invitations() {
	}

	public Invitations(String description, User sender, User reciever) {
		super();
		this.description = description;
		this.sender = sender;
		this.reciever = reciever;
		this.id = new InvitationsId(reciever.getId(), sender.getId());
	}

	public Invitations(User sender, User reciever) {
		super();
		this.sender = sender;
		this.reciever = reciever;
		this.id = new InvitationsId(reciever.getId(), sender.getId());
	}

	public Invitations(InvitationsId id, String description, int pageId) {
		this.id = id;
		this.description = description;
		this.pageId = pageId;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "receiverUserId", column = @Column(name = "ReceiverUserId", nullable = false, length = 128)),
			@AttributeOverride(name = "senderUserId", column = @Column(name = "SenderUserId", nullable = false, length = 128)) })
	public InvitationsId getId() {
		return this.id;
	}

	public void setId(InvitationsId id) {
		this.id = id;
	}

	@Column(name = "Description", nullable = true)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "PageId", nullable = false)
	public int getPageId() {
		return this.pageId;
	}

	public void setPageId(int pageId) {
		this.pageId = pageId;
	}

	@ManyToOne
	@JoinColumn(name = "senderUserId", referencedColumnName = "id", updatable = false, insertable = false)
	public User getSender() {
		return sender;
	}

	public void setSender(User sender) {
		this.sender = sender;
	}

	@ManyToOne
	@JoinColumn(name = "receiverUserId", referencedColumnName = "id", updatable = false, insertable = false)
	public User getReciever() {
		return reciever;
	}

	public void setReciever(User reciever) {
		this.reciever = reciever;
	}

}
