package com.esprit.hypnotrip.persistence;
// Generated 19 nov. 2016 19:30:02 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Media generated by hbm2java
 */
@Entity
@Table(name = "media", catalog = "hypnodb")
public class Media implements java.io.Serializable {

	private Integer mediaId;
	private int mediaType;
	private Integer postId;

	public Media() {
	}

	public Media(int mediaType) {
		this.mediaType = mediaType;
	}

	public Media(int mediaType, Integer postId) {
		this.mediaType = mediaType;
		this.postId = postId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "MediaId", unique = true, nullable = false)
	public Integer getMediaId() {
		return this.mediaId;
	}

	public void setMediaId(Integer mediaId) {
		this.mediaId = mediaId;
	}

	@Column(name = "MediaType", nullable = false)
	public int getMediaType() {
		return this.mediaType;
	}

	public void setMediaType(int mediaType) {
		this.mediaType = mediaType;
	}

	@Column(name = "PostId")
	public Integer getPostId() {
		return this.postId;
	}

	public void setPostId(Integer postId) {
		this.postId = postId;
	}

}
