package com.esprit.hypnotrip.persistence;
// Generated 19 nov. 2016 19:30:02 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MessagesId generated by hbm2java
 */
@Embeddable
public class MessagesId implements java.io.Serializable {

	private Date dateOfSending;
	private String receiverUserId;
	private String senderUserId;

	public MessagesId() {
	}

	public MessagesId(Date dateOfSending, String receiverUserId, String senderUserId) {
		this.dateOfSending = dateOfSending;
		this.receiverUserId = receiverUserId;
		this.senderUserId = senderUserId;
	}

	@Column(name = "DateOfSending", nullable = false, length = 0)
	public Date getDateOfSending() {
		return this.dateOfSending;
	}

	public void setDateOfSending(Date dateOfSending) {
		this.dateOfSending = dateOfSending;
	}

	@Column(name = "ReceiverUserId", nullable = false, length = 128)
	public String getReceiverUserId() {
		return this.receiverUserId;
	}

	public void setReceiverUserId(String receiverUserId) {
		this.receiverUserId = receiverUserId;
	}

	@Column(name = "SenderUserId", nullable = false, length = 128)
	public String getSenderUserId() {
		return this.senderUserId;
	}

	public void setSenderUserId(String senderUserId) {
		this.senderUserId = senderUserId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MessagesId))
			return false;
		MessagesId castOther = (MessagesId) other;

		return ((this.getDateOfSending() == castOther.getDateOfSending())
				|| (this.getDateOfSending() != null && castOther.getDateOfSending() != null
						&& this.getDateOfSending().equals(castOther.getDateOfSending())))
				&& ((this.getReceiverUserId() == castOther.getReceiverUserId())
						|| (this.getReceiverUserId() != null && castOther.getReceiverUserId() != null
								&& this.getReceiverUserId().equals(castOther.getReceiverUserId())))
				&& ((this.getSenderUserId() == castOther.getSenderUserId())
						|| (this.getSenderUserId() != null && castOther.getSenderUserId() != null
								&& this.getSenderUserId().equals(castOther.getSenderUserId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getDateOfSending() == null ? 0 : this.getDateOfSending().hashCode());
		result = 37 * result + (getReceiverUserId() == null ? 0 : this.getReceiverUserId().hashCode());
		result = 37 * result + (getSenderUserId() == null ? 0 : this.getSenderUserId().hashCode());
		return result;
	}

}
