package com.esprit.hypnotrip.persistence;
// Generated 19 nov. 2016 19:30:02 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Offer generated by hbm2java
 */
@Entity
@Table(name = "offer", catalog = "hypnodb")
public class Offer implements java.io.Serializable {

	private int pageId;
	private Date beginDate;
	private Date finishDate;

	public Offer() {
	}

	public Offer(int pageId, Date beginDate, Date finishDate) {
		this.pageId = pageId;
		this.beginDate = beginDate;
		this.finishDate = finishDate;
	}

	@Id

	@Column(name = "PageId", unique = true, nullable = false)
	public int getPageId() {
		return this.pageId;
	}

	public void setPageId(int pageId) {
		this.pageId = pageId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "BeginDate", nullable = false, length = 0)
	public Date getBeginDate() {
		return this.beginDate;
	}

	public void setBeginDate(Date beginDate) {
		this.beginDate = beginDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FinishDate", nullable = false, length = 0)
	public Date getFinishDate() {
		return this.finishDate;
	}

	public void setFinishDate(Date finishDate) {
		this.finishDate = finishDate;
	}

}
