package com.esprit.hypnotrip.persistence;
// Generated 19 nov. 2016 19:30:02 by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * Posts generated by hbm2java
 */
@Entity
@Table(name = "posts", catalog = "hypnodb")
public class Posts implements java.io.Serializable {

	private Integer postId;
	private String content;
	private String description;
	private String idOwner;
	private Integer pageId;
	private Date publicationPost;
	private Integer tagId;
	private Tags tag;

	public Posts() {
	}

	public Posts(String idOwner, Date publicationPost) {
		this.idOwner = idOwner;
		this.publicationPost = publicationPost;
	}

	public Posts(String content, String description, String idOwner, Integer pageId, Date publicationPost,
			Integer tagId) {
		this.content = content;
		this.description = description;
		this.idOwner = idOwner;
		this.pageId = pageId;
		this.publicationPost = publicationPost;
		this.tagId = tagId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PostId", unique = true, nullable = false)
	public Integer getPostId() {
		return this.postId;
	}

	public void setPostId(Integer postId) {
		this.postId = postId;
	}

	@Column(name = "Content")
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "Description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "IdOwner", nullable = false, length = 128)
	public String getIdOwner() {
		return this.idOwner;
	}

	public void setIdOwner(String idOwner) {
		this.idOwner = idOwner;
	}

	@Column(name = "PageId")
	public Integer getPageId() {
		return this.pageId;
	}

	public void setPageId(Integer pageId) {
		this.pageId = pageId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PublicationPost", nullable = false, length = 0)
	public Date getPublicationPost() {
		return this.publicationPost;
	}

	public void setPublicationPost(Date publicationPost) {
		this.publicationPost = publicationPost;
	}

	@Column(name = "TagId")
	public Integer getTagId() {
		return this.tagId;
	}

	public void setTagId(Integer tagId) {
		this.tagId = tagId;
	}

	@Transient
	public Tags getTag() {
		return tag;
	}

	public void setTag(Tags tag) {
		this.tag = tag;
	}

	@Override
	public String toString() {
		return "Posts [postId=" + postId + ", content=" + content + ", description=" + description + ", idOwner="
				+ idOwner + ", pageId=" + pageId + ", publicationPost=" + publicationPost + ", tagId=" + tagId
				+ ", tag=" + tag + "]";
	}

}
