package com.esprit.hypnotrip.persistence;

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Rates generated by hbm2java
 */
@Entity
@Table(name = "rates", catalog = "hypnodb")
public class Rates implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private RatesId id;
	private int niveau;
	private Date dateRating;

	private User user;
	private Pages page;

	public Rates() {
	}

	public Rates(RatesId id, Date dateRating, int niveau) {
		this.id = id;
		this.niveau = niveau;
	}

	@EmbeddedId

	@AttributeOverrides({
		@AttributeOverride(name = "pageId", column = @Column(name = "PageId", nullable = false) ),
		@AttributeOverride(name = "id", column = @Column(name = "UserId", nullable = false, length = 128) ) })
	public RatesId getId() {
		return this.id;
	}

	public void setId(RatesId id) {
		this.id = id;
	}

	@Column(name = "Niveau", nullable = false)
	public int getNiveau() {
		return this.niveau;
	}

	public void setNiveau(int niveau) {
		this.niveau = niveau;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateRating", nullable = false)
	public Date getdateRating() {
		return this.dateRating;
	}

	public void setdateRating(Date dateRating) {
		this.dateRating = dateRating;
	}

	@ManyToOne
	@JoinColumn(name = "userId", referencedColumnName = "id", insertable = false, updatable = false)
	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@ManyToOne
	@JoinColumn(name = "pageId", referencedColumnName = "pageId", insertable = false, updatable = false)
	public Pages getPage() {
		return page;
	}

	public void setPage(Pages page) {
		this.page = page;
	}

}
