package com.esprit.hypnotrip.persistence;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Rates generated by hbm2java
 */
@Entity
@Table(name = "rates", catalog = "hypnodb")
public class Rates implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private RatesId id;
	private int niveau;
	private Date dateRating;
	
	@ManyToOne
	@JoinColumn(name = "id_user", insertable = false, updatable = false)
	private User user;
	@ManyToOne
	@JoinColumn(name = "id_page", insertable = false, updatable = false)
	private Pages page;

	public Rates() {
	}

	public Rates(RatesId id, Date dateRating, int niveau) {
		this.id = id;
		this.niveau = niveau;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "Id", nullable = false, length = 128) ),
			@AttributeOverride(name = "pageId", column = @Column(name = "PostId", nullable = false) ) })
	public RatesId getId() {
		return this.id;
	}

	public void setId(RatesId id) {
		this.id = id;
	}

	

	@Column(name = "Niveau", nullable = false)
	public int getNiveau() {
		return this.niveau;
	}

	public void setNiveau(int niveau) {
		this.niveau = niveau;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateRating", nullable = false)
	public Date getdateRating() {
		return this.dateRating;
	}

	public void setdateRating(Date dateRating) {
		this.dateRating = dateRating;
	}
}
