package com.esprit.hypnotrip.persistence;
// Generated 19 nov. 2016 19:30:02 by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tickets generated by hbm2java
 */
@Entity
@Table(name = "tickets", catalog = "hypnodb")
public class Tickets implements java.io.Serializable {

	private Integer ticketId;
	private String label;
	private float price;
	private String description;
	private Integer numberOfPlaces;

	private Pages event;

	private List<BookDescription> bookDescriptions;

	public Tickets() {
	}

	public Tickets(float price) {
		this.price = price;

	}



	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "TicketId", unique = true, nullable = false)
	public Integer getTicketId() {
		return this.ticketId;
	}

	public void setTicketId(Integer ticketId) {
		this.ticketId = ticketId;
	}

	@Column(name = "Price", nullable = false, precision = 12, scale = 0)
	public float getPrice() {
		return this.price;
	}

	public void setPrice(float price) {
		this.price = price;
	}





	@OneToMany(mappedBy = "ticket",  fetch = FetchType.EAGER,cascade= CascadeType.ALL)
	public List<BookDescription> getBookDescriptions() {
		return bookDescriptions;
	}

	public void setBookDescriptions(List<BookDescription> bookDescriptions) {
		this.bookDescriptions = bookDescriptions;
	}

	@ManyToOne
	public Pages getEvent() {
		return event;
	}

	public void setEvent(Pages event) {
		this.event = event;
	}

	public Integer getNumberOfPlaces() {
		return numberOfPlaces;
	}

	public void setNumberOfPlaces(Integer numberOfPlaces) {
		this.numberOfPlaces = numberOfPlaces;
	}

	public String getLabel() {
		return label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
