package com.esprit.hypnotrip.persistence;
// Generated 19 nov. 2016 19:30:02 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Touristicplace generated by hbm2java
 */
@Entity
@Table(name = "touristicplace", catalog = "hypnodb")
public class Touristicplace implements java.io.Serializable {

	private int pageId;
	private Date dateOfCreation;
	private String logo;
	private String name;

	public Touristicplace() {
	}

	public Touristicplace(int pageId, Date dateOfCreation) {
		this.pageId = pageId;
		this.dateOfCreation = dateOfCreation;
	}

	public Touristicplace(int pageId, Date dateOfCreation, String logo, String name) {
		this.pageId = pageId;
		this.dateOfCreation = dateOfCreation;
		this.logo = logo;
		this.name = name;
	}

	@Id

	@Column(name = "PageId", unique = true, nullable = false)
	public int getPageId() {
		return this.pageId;
	}

	public void setPageId(int pageId) {
		this.pageId = pageId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DateOfCreation", nullable = false, length = 0)
	public Date getDateOfCreation() {
		return this.dateOfCreation;
	}

	public void setDateOfCreation(Date dateOfCreation) {
		this.dateOfCreation = dateOfCreation;
	}

	@Column(name = "Logo")
	public String getLogo() {
		return this.logo;
	}

	public void setLogo(String logo) {
		this.logo = logo;
	}

	@Column(name = "Name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
